
services:
  anytype:
    build: . # If you want build locally using docker-compose
    container_name: anytype
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data:/config/.config/anytype
    ports:
      - 3002:3000
      - 3001:3001
    restart: unless-stopped